# Generated by Django 3.1.7 on 2021-03-08 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0001_initial'),
        ('announcement', '0001_initial'),
        ('productor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='productor',
            name='idAnun',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='announcement.announcement'),
        ),
        migrations.AddField(
            model_name='productor',
            name='idPicture',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='picture.picture'),
        ),
    ]
