# Generated by Django 3.1.7 on 2021-03-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productor', '0002_auto_20210308_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productor',
            name='email',
            field=models.EmailField(max_length=30),
        ),
    ]
