# Generated by Django 3.1.7 on 2021-05-05 23:03

from django.db import migrations, models
import hortum.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210505_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='person-male.png', null=True, upload_to=hortum.users.models.upload_image),
        ),
    ]
