# Generated by Django 3.1.7 on 2021-05-01 14:53

from django.db import migrations, models
import hortum.complaint.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=450)),
                ('image', models.ImageField(null=True, upload_to=hortum.complaint.models.Complaint.upload_image)),
                ('emailCustomer', models.EmailField(max_length=100)),
            ],
        ),
    ]
