# Generated by Django 3.1.7 on 2021-05-11 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0002_complaint_idproductor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='author',
            field=models.CharField(max_length=30),
        ),
    ]
