# Generated by Django 3.1.7 on 2021-04-20 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productor', '0002_productor_user'),
        ('picture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('emailCustomer', models.EmailField(max_length=100, unique=True)),
                ('idPicture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='picture.picture')),
                ('idProductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='productor.productor')),
            ],
        ),
    ]
