# Generated by Django 3.1.7 on 2021-04-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='emailCustomer',
            field=models.EmailField(max_length=100),
        ),
    ]
