# Generated by Django 3.1.7 on 2021-03-11 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('picture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('inventory', models.BooleanField(default=False)),
                ('idPicture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='picture.picture')),
            ],
        ),
    ]
