# Generated by Django 3.1.7 on 2021-03-08 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0001_initial'),
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='idPicture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='picture.picture'),
        ),
    ]
