# Generated by Django 3.1.7 on 2021-04-28 21:36

from django.db import migrations, models
import hortum.announcement.models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_announcement_idproductor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementimage',
            name='picture',
            field=models.ImageField(default='src/hortum/img/person-male.png', null=True, upload_to=hortum.announcement.models.AnnouncementImage.upload_image_announ),
        ),
    ]
