# Generated by Django 3.1.7 on 2021-03-24 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('picture', '0001_initial'),
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idAnunFav', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='announcement.announcement')),
                ('idPicture', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='picture.picture')),
            ],
        ),
    ]
