# Generated by Django 3.1.7 on 2021-03-08 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('picture', '0001_initial'),
        ('announcement', '0001_initial'),
        ('productor', '0002_auto_20210308_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('idAnunFav', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='announcement.announcement')),
                ('idPicture', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='picture.picture')),
                ('idProdFav', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productor.productor')),
            ],
        ),
    ]
