# Generated by Django 3.1.7 on 2021-04-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_announcement_idproductor'),
        ('customer', '0003_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='idAnunFav',
        ),
        migrations.AddField(
            model_name='customer',
            name='idAnunFav',
            field=models.ManyToManyField(to='announcement.Announcement'),
        ),
    ]
