# Generated by Django 3.1.7 on 2021-04-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productor', '0002_productor_user'),
        ('customer', '0004_auto_20210416_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='idProdFav',
        ),
        migrations.AddField(
            model_name='customer',
            name='idProdFav',
            field=models.ManyToManyField(to='productor.Productor'),
        ),
    ]
